variables:
  VERSION: 0.0.6
  LUALATEX: lualatex --interaction=nonstopmode --output-directory ./out
  texstyle_dir: src/texstyle/out
  notes_dir: src/notes/out

default:
  image: registry.gitlab.com/quantumanon/texstyle/texstyle-container:latest
  before_script:
    - sh configure


stages:
  - build
  - test
  - docs
  - deploy


build-texstyle:
  stage: build
  only:
    - master
    - develop
  artifacts:
    expire_in: 1 hour
    paths:
      - src/texstyle/out/texstyle.sty
  script:
    - make --debug=b texstyle

build-notes:
  stage: build
  only:
    - master
    - develop
  artifacts:
    expire_in: 1 hour
    paths:
      - src/notes/out/texstyle-notes.cls
  script:
    - make --debug=b notes


test-texstyle:
  stage: test
  only:
    - master
    - develop
  dependencies:
    - build-texstyle
  script:
    - make -t src/texstyle/out/texstyle.sty
    - make --debug=b test-texstyle

test-notes:
  stage: test
  only:
    - master
    - develop
  dependencies:
    - build-notes
  script:
    - make -t src/notes/out/texstyle-notes.pdf
    - make --debug=b test-notes


docs-texstyle:
  stage: docs
  only:
    - master
    - develop
  artifacts:
    expire_in: 1 hour
    paths:
      - src/texstyle/out/texstyle.pdf
  dependencies:
    - build-texstyle
  script:
    - make -t src/texstyle/out/texstyle.sty
    - make --debug=b docs-texstyle

docs-notes:
  stage: docs
  only:
    - master
    - develop
  artifacts:
    expire_in: 1 hour
    paths:
      - src/notes/out/texstyle-notes.pdf
  dependencies:
    - build-notes
  script:
    - make -t src/notes/out/texstyle-notes.cls
    - make --debug=b docs-notes


package:
  image: alpine
  stage: deploy
  only:
    - master
    - develop
  artifacts:
    paths:
      - "builds/${VERSION}"
  before_script:
    - apk add zip tar make --debug=b
    - sh configure
  dependencies:
    - build-texstyle
    - build-notes
    - docs-texstyle
    - docs-notes
  script:
    - make -t src/texstyle/out/texstyle.sty
    - make -t src/notes/out/texstyle-notes.cls
    - make -t src/texstyle/out/texstyle.pdf
    - make -t src/notes/out/texstyle-notes.pdf
    - make --debug=b package
