variables:
  VERSION: 0.0.6
  LUALATEX: lualatex --interaction=nonstopmode --output-directory ./out
  texstyle_dir: src/texstyle/out
  notes_dir: src/notes/out

default:
  image: registry.gitlab.com/quantumanon/texstyle/build-test-container:latest
  before_script:
    - sh configure


stages:
  - build
  - test
  - docs
  - deploy


build-texstyle:
  stage: build
  only:
    - master
    - develop
  artifacts:
    expire_in: 1 hour
    paths:
      - src/texstyle/out/texstyle.sty
  script:
    - make texstyle

build-notes:
  stage: build
  only:
    - master
    - develop
  artifacts:
    expire_in: 1 hour
    paths:
      - src/notes/out/texstyle-notes.cls
  script:
    - make notes


test-texstyle:
  stage: test
  only:
    - master
    - develop
  dependencies:
    - build-texstyle
  script:
    - make -t src/texstyle/out/texstyle.sty
    - make test-texstyle

test-notes:
  stage: test
  only:
    - master
    - develop
  dependencies:
    - build-notes
  script:
    - make -t src/notes/out/texstyle-notes.cls
    - make test-notes


docs-texstyle:
  stage: docs
  image: registry.gitlab.com/quantumanon/texstyle/texstyle-container:latest
  only:
    - master
    - develop
  artifacts:
    expire_in: 1 hour
    paths:
      - src/texstyle/out/texstyle.pdf
  dependencies:
    - build-texstyle
  script:
    - make -t src/texstyle/out/texstyle.sty
    - make docs-texstyle

docs-notes:
  stage: docs
  image: registry.gitlab.com/quantumanon/texstyle/texstyle-container:latest
  only:
    - master
    - develop
  artifacts:
    expire_in: 1 hour
    paths:
      - src/notes/out/texstyle-notes.pdf
  dependencies:
    - build-notes
  script:
    - make -t src/notes/out/texstyle-notes.cls
    - make docs-notes


package:
  image: registry.gitlab.com/quantumanon/texstyle/packaging-container:latest
  stage: deploy
  only:
    - master
  artifacts:
    paths:
      - "builds/${VERSION}"
  dependencies:
    - build-texstyle
    - build-notes
    - docs-texstyle
    - docs-notes
  script:
    - make -t src/texstyle/out/texstyle.sty
    - make -t src/notes/out/texstyle-notes.cls
    - make -t src/texstyle/out/texstyle.pdf
    - make -t src/notes/out/texstyle-notes.pdf
    - make package
